extends: "airbnb"
parser: "babel-eslint"
plugins:
  - import
  - react
  - jsx-a11y
settings:
 "import/resolver":
  - babel-module
env:
  browser: true
  es6: true
rules:
  react/prop-types: 1
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
